imports:
    - { resource: "@DHArtisCmsPlugin/Resources/config/grids/admin/frequently_asked_question_section.yml" }
    - { resource: "@DHArtisCmsPlugin/Resources/config/grids/admin/map_point.yml" }
    - { resource: "@DHArtisCmsPlugin/Resources/config/grids/admin/catalog.yml" }
