imports:
    - { resource: "@BitBagSyliusCmsPlugin/Resources/config/config.yml" }
    - { resource: "@DHArtisCmsPlugin/Resources/config/services.yml" }
    - { resource: "@DHArtisCmsPlugin/Resources/config/resources.yml" }
    - { resource: "@DHArtisCmsPlugin/Resources/config/grids.yml" }
    - { resource: "@DHArtisCmsPlugin/Resources/config/packages/*.yml" }

parameters:
    artis_cms.public_dir: '%kernel.project_dir%/public'

twig:
    globals:
        public_dir: "%artis_cms.public_dir%"
