imports:
    - { resource: services/action.yml }
    - { resource: services/form.yml }
    - { resource: services/event_listener.yml }
    - { resource: services/factory.yml }
    - { resource: viewRepository/page.yml }

services:
    artis_sylius_cms_plugin.menu.content_management:
        class: DH\ArtisCmsPlugin\Menu\ContentManagementMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: buildMenu }

    artis_sylius_cms_plugin.menu.catalog_management:
        class: DH\ArtisCmsPlugin\Menu\CatalogMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: buildMenu }
