DH\ArtisCmsPlugin\Entity\CatalogImages:
    properties:
        file:
            - Image:
                  uploadIniSizeErrorMessage: artis_cms_plugin.product_image.file.upload_ini_size
                  groups: ['artis']
