DH\ArtisCmsPlugin\Entity\FrequentlyAskedQuestionSection:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
              fields: [code]
              message: 'artis_cms_plugin.frequently_asked_question_section.code.unique'
              groups: ['artis']
    properties:
        code:
            - NotBlank:
                  message: 'artis_cms_plugin.frequently_asked_question_section.code.not_blank'
                  groups: ['artis']
            - Length:
                  min: 2
                  max: 250
                  minMessage: 'artis_cms_plugin.frequently_asked_question_section.code.min_length'
                  maxMessage: 'artis_cms_plugin.frequently_asked_question_section.code.max_length'
                  groups: ['artis']
        translations:
            - Valid: ~
