sylius_resource:
    resources:
        bitbag_sylius_cms_plugin.frequently_asked_question:
            classes:
                model: DH\ArtisCmsPlugin\Entity\FrequentlyAskedQuestion
                repository: DH\ArtisCmsPlugin\Repository\FrequentlyAskedQuestionRepository
