sylius_grid:
    grids:
        artis_cms_plugin_admin_catalog:
            driver:
                name: doctrine/orm
                options:
                    class: "%artis_cms_plugin.model.catalog.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments: ["%locale%"]
            sorting:
                menuCode: asc
            limits: [10, 25, 50]
            fields:
                menuCode:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                title:
                    type: string
                    label: sylius.ui.title
                    sortable: ~
                subtitle:
                    type: string
                    label: artis_cms_plugin.ui.subtitle
                    sortable: ~
                year:
                    type: twig
                    label: artis_cms_plugin.ui.year
                    options:
                        template: "@DHArtisCmsPlugin/Catalog/Grid/Field/year.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [menuCode]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
