sylius_grid:
    grids:
        artis_cms_plugin_admin_map_point:
            driver:
                name: doctrine/orm
                options:
                    class: "%artis_cms_plugin.model.map_point.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments: ["%locale%"]
            sorting:
                code: asc
            limits: [10, 25, 50]
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: translation.name
                city:
                    type: string
                    label: sylius.ui.city
                    sortable: ~
                openingHours:
                    type: string
                    label: artis_cms_plugin.ui.opening_hours
                    sortable: ~
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
