artis_sylius_cms_plugin_admin_map_point:
    resource: |
        alias: artis_cms_plugin.map_point
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: update
        grid: artis_cms_plugin_admin_map_point
        except: ['show']
        permission: true
        vars:
            all:
                header: artis_cms_plugin.ui.map_points_header
                subheader: artis_cms_plugin.ui.map_points_subheader
                templates:
                    form: "@DHArtisCmsPlugin/MapPoint/Crud/_form.html.twig"
            index:
                icon: sticky note
    type: sylius.resource
